# Comparison of Spatial Interpolation Methods for the Estimation of Seoul’s Air Pollution {#study1}
**Overview**

This chapter firstly explores the pollution data in different time sequences and types of monitoring stations.
Then it compares two spatial interpolation methods, Universal Kriging, GAM, with additional weights on road layers as an effect of roadside pollution fields. 
After the calibration and validation, this chapter finally discusses issues relevant to interpolation methods and health effects.


## Data list
This chapter explores the spatial and temporal patterns of pollution in Seoul as well as the extent to which background and roadside stations are similar or different. The NIER (National Institute of Environmental Research) provided 6 pollutants, PM~10~, PM~2.5~, NO~2~, CO, SO~2~, O~3~, which were released as an hourly aggregation. This study selected PM~10~ as the main source that can causally result in human cancer and NO~2~ as the main source that harms respiratory symptoms, whether constantly or instantaneously [@WHO2013].


Pollution data were collected from two different types of stations: background stations (installed on the rooftops of district offices), and roadside stations (close to the major roads which are strongly affected by nearby traffic). This study took into account 57 urban background stations and 19 roadside stations that were within 10km from the city boundary (see Figure~\@refpollution_stations). 
Amongst these 76 stations, Seoul itself had 25 background stations and 15 roadside stations. Roadside data were retrieved from the 19 stations installed on the roads near the city centre, 8-lane junctions, and a highway entrance. The possible download period was between 01/01/2010 01:00 and 01/01/2018 00:00. Units are measured in ppb (parts per billion) for NO~2~, and µg/m^3^ for PM~10~.



## What the data looks like: Exploration with R


## Output: Univeral Kriging 


## Output: Generalised Additive Models


## Summary






